### ISSUE TITLE
Unite file_rec source shows absolute paths instead of relative

### ISSUE THREAD

**Issue by sergei-dyshel** [ryanoasis/vim-devicons#140]
Hi,
When `g:webdevicons_enable_unite == 1` and running Unite with `Unite -start-insert buffer file_rec/async:.` it show absolute file paths instead of relative.
When  `g:webdevicons_enable_unite == 1`, it works as expected.

**Comment by sergei-dyshel** [comment]
Also mentioned here https://github.com/Shougo/unite.vim/issues/991

**Comment by ryanoasis** [comment]
@sergei-dyshel Thanks! Confirmed.

I think I remember seeing https://github.com/Shougo/unite.vim/issues/991 a while back but never created a ticket or took the time to dig into it.

Seems like when it is buffer we are printing out the filename and path. should probably just be filename in this scenario.

---

for reference: 

seems to have occured with fix/change: https://github.com/ryanoasis/vim-devicons/commit/a2823ff954842c6bdf02f558833ad9558813b41c (#86)

I haven't tested thoroughly but I think the suitable change would be:
```vim
" prevent filenames of buffers getting 'lost'
if filename != path
    let path = printf("%s", filename)
endif
```

instead of: https://github.com/ryanoasis/vim-devicons/blob/d0111ec77c3d7e3e3072e576bb26055643e64a2f/plugin/webdevicons.vim#L415

**Comment by ryanoasis** [comment]
Please try out [0.8.1](https://github.com/ryanoasis/vim-devicons/tree/0.8.1) branch. If no feedback or no issues reported I will merge into master Monday. Thanks :bow:
