### ISSUE TITLE
icon for java class and interface respectively

### ISSUE THREAD

**Issue by jackiilong** [ryanoasis/vim-devicons#241]

**Comment by kutsan** [comment]
We are not all Java developers here. Could you please explain what you are trying to say a little bit more?

If you are saying there should be a dropdown menu or something under file name to show classes, interfaces inside that file with icons like IntelliJ IDEA's feature; this is not our problem because this repository only contains support for vim file icons. You need to create that issue under your vim file manager's repository.

**Comment by kutsan** [comment]
As I said above, this is not our concern. I'm going to close this issue for now but if you think I got something wrong, we can re-open it.
