### ISSUE TITLE
Folders and files are badly aligned

### ISSUE THREAD

**Issue by olalonde** [ryanoasis/vim-devicons#248]
<img width="279" alt="screenshot 2018-10-29 01 20 58" src="https://user-images.githubusercontent.com/416585/47619485-0d165480-db1a-11e8-87af-4373f0b11df4.png">

It makes it hard to see which files and folders belong to the same parent folder, especially when brackets are disabled. Which settings can I change to improve this? An option would be to have the folder have icons too so that every file/folder in a given folder is vertically aligned. 

I'm using 15pt Inconsolota Nerd Font Complete in iTerm2.

**Comment by leisurelicht** [comment]
+1

**Comment by kutsan** [comment]
Hi there Oli! I'm here to debug this problem but in order to reproduce, can you please include a `.vimrc` file with bare-minimum configuration in it? And before do that, just to make sure, update `devicons` and `nerdtree` plugins to their latest version.

**Comment by maksbotan** [comment]
Hi @kutsan! I also has this problem. My minimal vimrc:

```vim
set termguicolors
call plug#begin('~/.local/share/nvim/plugged')

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'ryanoasis/vim-devicons'

call plug#end()
```

I'm using nvim v0.3.2-dev (neovim/neovim@1cca5da05) built from git using homebrew, nerdtree at scrooloose/nerdtree@72c3656799289d4635520c28e17f737066ce19d6, devicons at ryanoasis/vim-devicons@ea5bbf0e2a960965accfa50a516773406a5b6b26 and Hack Nerd Font.

Here's how it looks with that minimal config:
![image](https://user-images.githubusercontent.com/275614/49936388-eacb7100-fee4-11e8-80b2-3f08d21edc1e.png)

**Comment by kutsan** [comment]
Well, turns out it was way bigger problem than I initially thought. The problem involves for users who has set `g:WebDevIconsUnicodeDecorateFolderNodes` to `v:false` and it is `v:false` by default. Since each Unicode icon need an extra space before them to show up correctly, there is a space padding for them. Although, we also add an extra padding by default just in case. You can remove that extra space by doing this:

```vim
let g:WebDevIconsNerdTreeBeforeGlyphPadding = ""
```

![image](https://user-images.githubusercontent.com/10108377/49956644-ba9cc600-ff16-11e8-8e8e-aaf53572c968.png)

> with default settings.

![image](https://user-images.githubusercontent.com/10108377/49956655-c38d9780-ff16-11e8-8725-ccf9bc7ac1c8.png)

> with `let g:WebDevIconsNerdTreeBeforeGlyphPadding = ""`

See the difference? Now, it is somewhat aligned but not quite.

My recommendation is to enable folder icons and then they also will have that padding thus this makes them aligned.

```vim
let g:WebDevIconsUnicodeDecorateFolderNodes = v:true
```

![image](https://user-images.githubusercontent.com/10108377/49956717-f6d02680-ff16-11e8-96fe-d0d4e80fb2d7.png)

> `let g:WebDevIconsUnicodeDecorateFolderNodes = v:true`

Going further, I don't think we need those ugly arrows anymore, you can disable them by:

```vim
" Disable arrow icons at the left side of folders for NERDTree.
let g:NERDTreeDirArrowExpandable = "\u00a0"
let g:NERDTreeDirArrowCollapsible = "\u00a0"
```

![image](https://user-images.githubusercontent.com/10108377/49956787-18311280-ff17-11e8-8fa3-c6d7405ef4e0.png)

I think this is the best we can do for now. I'm not going to lie both vim-devicons and nerdtree itself are poorly written, due to this it is hard to fix those kind of bugs when we encounter.

And to fix folder icon color, see https://github.com/ryanoasis/vim-devicons/issues/250.

![image](https://user-images.githubusercontent.com/10108377/49957040-c341cc00-ff17-11e8-896d-8d5f6b0e9b0e.png)

> `highlight! link NERDTreeFlags NERDTreeDir`

**Comment by realestninja** [comment]
I can't wait to get home and try your findings! It looks great on your screenshot!

**Comment by zapashcanon** [comment]
Hi,

I opened this issue some time ago: https://github.com/scrooloose/nerdtree/issues/848

As long as it's open, I'm using my patched nerdtree (zapashcanon/nerdtree).

In case that could be of any help... :)

**Comment by kutsan** [comment]
@zapashcanon Since devicons plugin itself adds those spaces to make it work; I don't think that is relevant to this issue.

**Comment by maksbotan** [comment]
I can confirm that this solves issue for me :)
```vim
let g:WebDevIconsNerdTreeBeforeGlyphPadding = ""
let g:WebDevIconsUnicodeDecorateFolderNodes = v:true
```

Any chance of making this default or at least mentioning in the docs?

**Comment by realestninja** [comment]
`let g:WebDevIconsNerdTreeBeforeGlyphPadding = ""
let g:WebDevIconsUnicodeDecorateFolderNodes = v:true`

This definitely does the trick.

I also tried 
`" Disable arrow icons at the left side of folders for NERDTree.
let g:NERDTreeDirArrowExpandable = "\u00a0"
let g:NERDTreeDirArrowCollapsible = "\u00a0"`

This does take care of removing the arrows... But at the same time I can't expand/collapse folders in nerdtree anymore. Also pressing `p` to get to parent directory within nerdtree does not work anymore.

**Comment by kutsan** [comment]
@maksbotan 

> Any chance of making this default or at least mentioning in the docs?

It's planned. I think we need better code resolutions for our fatal bugs.

**Comment by maulanakmal** [comment]
nice, i really have strugling with that

**Comment by bandithijo** [comment]
but  this solution leave too much wide padding on the left side T_T

**Comment by kutsan** [comment]
@bandithijo There is not much we can do unfortunately. By the way, if you haven't, setting sign column to `no` reduces a little bit that space.

```vim
autocmd FileType nerdtree setlocal signcolumn=no
```

**Comment by cocobear** [comment]
I tried :
```
let g:WebDevIconsNerdTreeBeforeGlyphPadding = ""
let g:WebDevIconsUnicodeDecorateFolderNodes = v:true
autocmd FileType nerdtree setlocal signcolumn=no
```
But still got a log of padding before file names.

<img width="203" alt="vim-devicons-padding" src="https://user-images.githubusercontent.com/181942/51662917-41ea5880-1ff0-11e9-8225-6fe8d604f0b4.png">

```
nvim --version                                                                         
NVIM v0.3.4
```
I'm using 14pt 'font-sourcecodepro-nerd-font' in iTerm2.

**Comment by bandithijo** [comment]
@cocobear 
That padding cannot going anywhere for now.
But, maybe you want to hide that arrow with
```
"let g:NERDTreeDirArrowExpandable = '▸'
"let g:NERDTreeDirArrowCollapsible = '▾'
```
![screenshot from 2019-01-24 19-23-57](https://user-images.githubusercontent.com/3227736/51675350-67865a80-200e-11e9-8758-98a6e01c15eb.png)

Honestly, that is not too bad for me. I can love it! (^_^)

**Comment by ryanoasis** [comment]
@kutsan Thanks for taking the early look into it and providing great info and screenshots.

> I think we need better code resolutions for our fatal bugs.

Can you elaborate on this?

---

@cocobear I think at least some of the padding is likely because of `g:WebDevIconsNerdTreeGitPluginForceVAlign` which when set prepends padding to the glyph.

---

@maksbotan You are right it would make sense to have `let g:WebDevIconsUnicodeDecorateFolderNodes` on by default

---

I am working on this issue now (while looking into #223 again).

## WIP/RFC Behaviour

I have some changes that seem promising and more consistent behavior:

![alignment-selection_028](https://user-images.githubusercontent.com/8083459/52542026-bac80f00-2d69-11e9-99d6-ae7df0d02bfc.png)

![alignment-selection_029](https://user-images.githubusercontent.com/8083459/52542028-be5b9600-2d69-11e9-89f3-d92e46b11197.png)

![alignment-selection_030](https://user-images.githubusercontent.com/8083459/52542031-c1ef1d00-2d69-11e9-9d56-709a2d3cd8d8.png)

## WIP/RFC PR:

**Current WIP/RFC PR if anyone could try it out: #255**

**Comment by jerpint** [comment]
This took me way too long to find! Thanks @kutsan your solution worked perfectly for me.

Does anyone know of anyone who has added lines just like `tree` would in your terminal? i.e. something like

```
.
├── api
│   ├── app
│   │   ├── audio_processing.py
│   │   ├── database.py
│   │   ├── __init__.py
```

**Comment by polyzen** [comment]
> I tried :
> 
> ```
> let g:WebDevIconsNerdTreeBeforeGlyphPadding = ""
> let g:WebDevIconsUnicodeDecorateFolderNodes = v:true
> autocmd FileType nerdtree setlocal signcolumn=no
> ```
> 
> But still got a log of padding before file names.
> 
> <img alt="vim-devicons-padding" width="203" src="https://user-images.githubusercontent.com/181942/51662917-41ea5880-1ff0-11e9-8225-6fe8d604f0b4.png">
> 
> ```
> nvim --version                                                                         
> NVIM v0.3.4
> ```
> 
> I'm using 14pt 'font-sourcecodepro-nerd-font' in iTerm2.

Just to note, this seems to be 2048 em glyphs as opposed to 1000 em.
