### ISSUE TITLE
No space between icon and filename even with DevIconsAppendArtifactFix

### ISSUE THREAD

**Issue by twnaing** [ryanoasis/vim-devicons#333]
#### Required Info

- [x] I have searched the [issues](https://github.com/ryanoasis/vim-devicons/issues) for my issue and found nothing related and/or helpful
- [x] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting)
- [x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
- [x] `VimDevIcons` is the last loaded vim plugin? __yes__
- [x] What **version** of vim are you using? __neovim 0.4.3__
  - hint: `vim --version`
- [x] What **version** of vim-devicons are you using? __0.11.0__
  - hint: `:echo webdevicons#version()`
- [x] Are you using vim from the terminal or a GUI vim? __terminal__
- [x] Are you using Mac, Linux or Windows? __linux__

#### Optional Info

With this snippet I get the required output with [vim-dirvish](https://github.com/justinmk/vim-dirvish) except icon is too close to file name

```
let g:DevIconsAppendArtifactFix=1

augroup dirvish_config
    autocmd!
    autocmd FileType dirvish call dirvish#add_icon_fn({p ->  WebDevIconsGetFileTypeSymbol(p, p[-1:] == '/' ? 1 : 0) })
augroup END
```

```
echo g:DevIconsAppendArtifactFix # return 1
```

I want to know
- am I configuring wrong with `g:DevIconsAppendArtifactFix`?
- this issue does not relate to devicon?

**Comment by kazukazuinaina** [comment]
Thanks for report.
I'm not sure because I'm not using dirvish , but I think it's probably unrelated to devicons.

At the extreme, if you set a lot of space on the `g:DevIconsArtifactFixChar`, you can see that the airline reflects a lot of space as shown in the screenshot. It uses the same API `(WebDevIconsGetFileTypeSymbol())` you used.

```viml
let g:DevIconsArtifactFixChar = '            '
let g:DevIconsAppendArtifactFix = 1
```

## screen shot

<img width="562" alt="スクリーンショット 2020-05-27 17 23 04" src="https://user-images.githubusercontent.com/36619465/82995673-dc243b80-a03e-11ea-9791-a942e3929c8a.png">

I close this issue as irrelevant, but if you have any problems please restart this issue.
