### ISSUE TITLE
:CtrlPMRU now erroneously shows the current buffer.

### ISSUE THREAD

**Issue by washtubs** [ryanoasis/vim-devicons#88]
I didn't try to extensively reproduce this. I just noticed it after installing, so let me know if it's not easy to reproduce. I had to disable the plugin to fix.

`:CrtlPMRU` is supposed to automatically place your cursor on the previously opened buffer. Now it starts you on the *current* buffer, which you would obviously never need to switch to.

**Comment by ryanoasis** [comment]
@washtubs thanks and I will look into it. Sorry about that!

Just FYI if you want you can disable _just_ the ctrlp integration until this is fixed with:
```vim
let g:webdevicons_enable_ctrlp = 0
```

**Comment by ryanoasis** [comment]
after a lot of digging I found the key issue inside `s:MatchIt` because I am sending the items with an extra glyph/icon but the current item (`a:exc`) here does _NOT_ have the glyph so the match is failing causing the item to be added to the list when it shouldn't be.

This all relates to how I am actually modifying `s:mrufs` instead of modifying the `s:formatline()` method and the change would require overwriting a ton more CtrlP functions :cry: 

So I think what is going to happen is eventually I am going to drop support of [Kien's original repo](https://github.com/kien/ctrlp.vim) and only support the [ctrlpvim active fork CtrlP](https://github.com/ctrlpvim/ctrlp.vim) because I could submit a PR to make this a lot easier

Which one do you use by the way?

**Comment by washtubs** [comment]
I use kien's but until you mentioned it, I didn't know there was another one that was being actively maintained. Now I suppose I'll just switch to that one!

**Comment by ryanoasis** [comment]
:smile:

**Comment by ryanoasis** [comment]
Sorry for the late follow up. @washtubs is this still an issues?

If you use pull the latest https://github.com/ctrlpvim/ctrlp.vim it _should_ be fixed since my PR.

I will test this out tomorrow. Cheers.

**Comment by ryanoasis** [comment]
Actually, sorry this still looks to be an issue :cry:

**Comment by ryanoasis** [comment]
This is actually a very annoying UX , so I am going to try to work on it next after a few other ones are completed

**Comment by liuxyc** [comment]
this bug really prevent me using vim-devicons......   hope get fixed soon

**Comment by ryanoasis** [comment]
@liuxyc Sorry about that. Yes well I have a proposal for a solution (https://github.com/ctrlpvim/ctrlp.vim/issues/267) but waiting for a response and then I would submit a PR to ctrlp that would add support for logic on vimdevicons side to complete the fix

**Comment by ryanoasis** [comment]
The support needed in ctrlp has now been merged 🎉 . The vimdevicons portion will be added in the next release  (v0.9.0)

**Comment by ryanoasis** [comment]
Wow has it been this long? :blush: I will **try** to get this up this weekend. Thanks!
